config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'search_notebooks#index'

  get 'search_results_view', to: 'search#search_results_view', as: 'search_results_view'
  get 'statistics', to: 'statistics#get_statistics', as: "get_statistics"
  get 'tests', to: 'tests#tests', as: "tests"
  post 'check_data', to: 'tests#check_data', as: "check_data"

  resources :search_notebooks, only: [:create, :index, :show, :destroy, :update] do 
  end
   
  resources :search_results, only: [:create, :show, :destroy] do 
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/search_notebook.rb
class SearchNotebook < ActiveRecord::Base
    has_many :search_results

    validates :title, presence: true
end

app/models/search_query.rb
class SearchQuery < ActiveRecord::Base
    validates :query_string, presence: true    
end

app/models/search_result.rb
class SearchResult < ActiveRecord::Base
    belongs_to :search_notebook
    belongs_to :search_query
    
    validates :hn_author, :author_karma_points, :url, :creation_date, :search_query_id, :search_notebook, presence: true

end

app/models/tools/api_helper.rb
module Tools
    class ApiHelper
        require 'net/http'
        require 'json'

        def self.get_author_karma_points(author)
            response = Net::HTTP.get(URI("https://hn.algolia.com/api/v1/users/#{author.to_s}"))

            r = JSON.parse(response)
            r["karma"]
        end

        def self.check_data_correction(result)
            karma = Tools::ApiHelper.get_author_karma_points(result.hn_author)

            response = Net::HTTP.get(URI("https://hn.algolia.com/api/v1/search?tags=author_#{result.hn_author.to_s}&numericFilters=created_at_i=#{result.creation_date.to_i}"))

            r = JSON.parse(response)
            result_data = r["hits"].first
            if result_data.nil?
                return nil;
            end

            new_result = SearchResult.new(
                hn_author: result_data["author"],
                url: result_data["url"],
                creation_date: DateTime.parse(result_data["created_at"]),
                hn_tags: result_data["_tags"].join(','),
                search_query: query, 
                author_karma_points: karma
            )

            if new_result.attributes.except('id', 'created_at', 'updated_at') != result.attributes.except('id', 'created_at', 'updated_at')
                return new_result
            end

            nil
        end

        def initialize(query)
            @query = query 
        end

        def get_search_results(page)
            data = get_page_data(page)
            q =  SearchQuery.create!(
                query_string: data["query"],
                number_of_hits: data["nbHits"]
            )
            
            results = data["hits"].map do |hit|
                initialize_search_result(hit, q)
            end

            {:query => q, :results => results}
        end

        def initialize_search_result(result_data, query)
            SearchResult.new(
                hn_author: result_data["author"],
                url: result_data["url"],
                creation_date: DateTime.parse(result_data["created_at"]),
                hn_tags: result_data["_tags"].join(','),
                search_query: query
            )
        end

        def get_page_data(page)
            url = "https://hn.algolia.com/api/v1/search?#{@query}&page=#{page}"
            uri = URI(url)
            response = Net::HTTP.get(uri)

            JSON.parse(response)
        end
    end

end

app/models/tools/statistic_creator.rb
module Tools
    class StatisticCreator
        def get_statistics
            queries = SearchQuery.all.select{|q| q.created_at.to_date >= Date.today-6.days}
     
            puts SearchQuery.all.first.inspect
            queries.group_by{|q| q.query_string}.map do |query_string, search_queries|
                search_queries_last_day = search_queries.select{|q| q.created_at.to_date == Date.today-1.day}
                average_week = search_queries.length == 0 ? nil : (search_queries.map{|q| q.number_of_hits}.sum)/search_queries.length
                average_day = search_queries_last_day.length == 0 ? nil : (search_queries_last_day.map{|q| q.number_of_hits}.sum)/search_queries_last_day.length
                
                {
                    :query_string => query_string, 
                    :average_week => average_week,
                    :average_day => average_day
                }
            end
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    def search_results_view
        begin 
            unless (params["query"].nil?)
                @search_notebooks = SearchNotebook.all
                ah = Tools::ApiHelper.new(params["query"])
                @search_data = ah.get_search_results(params["page"] || 1)
            end
        rescue => e 
            flash[:danger] = "#{e.message}"
        end 
    end
end

app/controllers/search_notebooks_controller.rb
class SearchNotebooksController < ApplicationController
    before_action :set_notebook, only: [:show, :update]

    def index
        @search_notebooks = SearchNotebook.all
    end

    def show
        @results = @notebook.search_results
    end

    def create
        begin
            n = SearchNotebook.create!(notebook_params)
        rescue => e 
            flash[:danger] = "Creating failed: #{e.message}"
        end 
        
        redirect_to root_path
    end

    def update
        begin
            @notebook.update!(notebook_params)
        rescue => e 
            flash[:danger] = "Creating failed: #{e.message}"
        end 
        
        redirect_to root_path
    end

    def destroy 
        begin
            SearchNotebook.destroy(params[:id])
        rescue => e 
            flash[:danger] = "Destroying failed: #{e.message}"
        end
        redirect_to root_path 
    end

    private 
    def notebook_params
        params.require(:search_notebook).permit(:title)
    end

    def set_notebook
        @notebook = SearchNotebook.find params[:id]
    end

end

app/controllers/search_results_controller.rb
class SearchResultsController < ApplicationController
    before_action :set_result, only: [:show]

    def show

    end

    def create
        begin
            r = SearchResult.new(result_params)
            r.search_query_id = params['search_query_id']
            r.url = params['url']
            r.author_karma_points = Tools::ApiHelper.get_author_karma_points(r.hn_author)
            r.save!

            flash[:success] = "The result was saved"
        rescue => e 
            flash[:danger] = "Saving failed: #{e.message}"
        end 
       
       redirect_back fallback_location: search_results_view_path(query: params['query'] , page: params['page'] )
    end

    def destroy 
        begin
            notebook_id = SearchResult.find(params[:id]).search_notebook.id
            SearchResult.destroy(params[:id])     
        rescue => e 
            flash[:danger] = "Destroying failed: #{e.message}"
        end

        redirect_to search_notebook_path(notebook_id)         
    end

    private 
    def result_params
        params.require(:search_result).permit(:hn_author, :creation_date, :hn_tags, :search_notebook_id)
    end

    def set_result
        @result = SearchResult.find params[:id]
    end

end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
    def get_statistics
        sc = Tools::StatisticCreator.new
        @statistics = sc.get_statistics
    end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
    def tests
    end

    def check_data
        begin 
            SearchResult.all.each do |result|
                r = Tools::ApiHelper.check_data_correction(result)
                unless r.nil?
                    result.update!(r.attributes)
                    flash[:success] = "Results updated"
                end
            end
        rescue => e 
            flash[:danger] = "#{e.message}"
        end 
        redirect_to tests_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_header.html.slim
nav.navbar.navbar-default.navbar-static-top role="navigation" 
  .container-fluid
    a.navbar-brand 
      span.glyphicon.glyphicon-search
      |  Search Notebook Application
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        li= active_link_to "Notebooks", root_path, active: :exact
        li= active_link_to "Search view", search_results_view_path
        li= active_link_to "Statistics", get_statistics_path
        li= active_link_to "Tests", tests_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title SearchNotebookApplication
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'home/header'
    .container
      - flash.each do |name, msg|
        .alert.alert-info.alert-dismissable
          button type="button" class="close" data-dismiss="alert"
            | &times;
          = msg
      = yield

app/views/search/_pagination_panel.html.slim
- page = params["page"] || 1
.row
  - if page.to_i > 0
    = link_to params.permit(:query).merge({:page => page.to_i - 1}), :wrap_tag => :li, class: "btn btn-primary"
      = page.to_i - 1
  = link_to params.permit(:query).merge({:page => page}), :wrap_tag => :li, class: "btn btn-primary", disabled: true
    = page
  = link_to params.permit(:query).merge({:page => page.to_i + 1}), :wrap_tag => :li, class: "btn btn-primary"
    = page.to_i + 1
    

app/views/search/_search_form.html.slim
form action="search_results_view" method="get" enctype="multipart/form-data"
  .row.horizontal-form
    .col-md-10
      .form-group
        = label_tag 'query'
          | Query
        = text_field_tag :query, nil, class: 'form-control', value: params[:query]
    .col-md-2
      .form-group
        button.btn.custom-btn.btn-block type="submit" Submit

app/views/search/search_results_view.html.slim
= render 'search_form'

- unless @search_data.nil?
  = render "pagination_panel"
  - @search_data[:results].each do |result|
    = form_for :search_result, url: search_results_path, turboboost: true, method: :post  do |f|
      .panel.panel-default
        .panel-heading 
          = result.url
          .btn-group.pull-right
            button.btn.btn-xs.btn-primary type="submit"
              span.glyphicon.glyphicon-floppy-disk
              |  Save result
        .panel-body
          = hidden_field_tag 'url', result.url
          = hidden_field_tag 'search_query_id', result.search_query.id

          = hidden_field_tag 'query', params["query"]
          = hidden_field_tag 'page', params["page"]

          .row
            .col-md-3
              .form-group
                = f.label :hn_author, "Author"
                = f.text_field :hn_author, class: 'form-control', value: result.hn_author, readonly: true
            .col-md-3
              .form-group
                = f.label :creation_date, "Creation date"
                = f.text_field :creation_date, class: 'form-control', value: result.creation_date, readonly: true
            .col-md-3
              .form-group
                = f.label :hn_tags, "HN tags"
                = f.text_field :hn_tags, class: 'form-control', value: result.hn_tags, readonly: true
            .col-md-3
              .form-group
                = f.label :search_notebook_id, "Search notebook"
                = f.select :search_notebook_id, @search_notebooks.map{|sn| [sn.title, sn.id]}, {}, {class: 'form-control'}

app/views/search_notebooks/_add_notebook.html.slim
= form_for :search_notebook, url: search_notebooks_path, turboboost: true, method: :post  do |f|
  .modal.fade#add_notebook tabindex="-1" role="dialog"
    .modal-dialog role="document"
      .modal-content
        .modal-header Add notebook
        .modal-body
          .row
            .col-md-12
              .form-group
                = f.label :title, "Title"
                = f.text_field :title, class: 'form-control'
        .modal-footer
          button.btn.custom-btn type="submit" Save
          button.btn.btn-default data-dismiss="modal" Cancel

app/views/search_notebooks/_edit_form.html.slim
= form_for search_notebook, url: search_notebook_path(search_notebook),  turboboost: true, method: :patch  do |f|
  .modal.fade id="notebook_edit_#{search_notebook.id}" tabindex="-1" role="dialog"
    .modal-dialog role="document"
      .modal-content
        .modal-header Edit notebook
        .modal-body
          .row
            .col-md-12
              .form-group
                = f.label :title, "Title"
                = f.text_field :title, class: 'form-control'
        .modal-footer
          button.btn.custom-btn type="submit" Save
          button.btn.btn-default data-dismiss="modal" Cancel

app/views/search_notebooks/_edit_forms.html.slim
- @search_notebooks.each do |search_notebook|
  = render partial: 'edit_form', locals: {search_notebook: search_notebook}

app/views/search_notebooks/index.html.slim
.panel.panel-default
  .panel-heading 
    | Search notebooks
    .btn-group.pull-right
      button.btn.btn-xs data-toggle="modal" data-target="#add_notebook" type="button"
        span.glyphicon.glyphicon-plus
  .panel-body
    table.table.table-hover
      thead
        tr
          th width="90%" Notebook title
          th width="10%"
      tbody 
      - @search_notebooks.each do |n|
          tr 
            td 
              = link_to n.title, search_notebook_path(n) 
            td 
              .btn-group.pull-right
                button.btn.btn-xs data-toggle="modal" data-target="#notebook_edit_#{n.id}"
                  span.glyphicon.glyphicon-pencil
                =link_to search_notebook_path(n), class: 'btn btn-xs', method: :delete, data: {confirm: "Do you really want to delete this notebook?"}
                  span.glyphicon.glyphicon-remove

= render "add_notebook"
= render "edit_forms"

app/views/search_notebooks/show.html.slim
h3 =@notebook.title

button.btn.btn-xs data-toggle="modal" data-target="#notebook_edit_#{@notebook.id}"
    span.glyphicon.glyphicon-pencil

table.table.table-hover
  thead
    tr
      th width="25%" Author 
      th width="25%" URL
      th width="20%" Creation Date
      th width="25%" HN tags
      th width="5%"
  tbody
    - @results.each do |r|
      tr
        td = r.hn_author
        td = link_to r.url, search_result_path(r)
        td = r.creation_date
        td = r.hn_tags.gsub(',', ', ')
        td 
          .btn-group.pull-right
            =link_to search_result_path(r), class: 'btn btn-xs', method: :delete, data: {confirm: "Do you really want to delete this result?"}
              span.glyphicon.glyphicon-remove



= render partial: 'edit_form', locals: {search_notebook: @notebook}

app/views/search_results/show.html.slim
h3 Search result
.panel.panel-default
  .panel-heading = @result.url
  .panel-body
    .row
      .col-md-3
        b = "Author"
      .col-md-3
        = @result.hn_author
      .col-md-3
        b = "Creation date"
      .col-md-3
        = @result.creation_date
    .row
      .col-md-3
        b = "HN tags"
      .col-md-3
        - @result.hn_tags.split(",").each do |tag|
          p = tag
      .col-md-3
        b = "Notebook"
      .col-md-3
        = link_to @result.search_notebook.title, search_notebook_path(@result.search_notebook)

h4 Search query
- query = @result.search_query
.panel.panel-default
  .panel-heading = query.query_string
  .panel-body
    .row
      .col-md-6
        b = "Number of hits"
      .col-md-6
        = query.number_of_hits

app/views/statistics/get_statistics.html.slim
table.table.table-hover
  thead
    tr
      th width="33%" Search query 
      th width="33%" Average of total search results for the last day
      th width="33%" Average of total search results for the last week
  tbody
    - @statistics.each do |s|
      tr
        td = s[:query_string]
        td = s[:average_day]
        td = s[:average_week]
        